-- ============================================================================
-- JoyOps v3 : Skema Database
-- Jalankan di Supabase SQL Editor, sekali, dari atas ke bawah.
-- Urutan berkas: 01_schema.sql -> 02_seed.sql -> (03_auth_users.sql opsional)
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 0. Perpanjangan
-- ---------------------------------------------------------------------------
create extension if not exists pgcrypto with schema extensions;

-- ---------------------------------------------------------------------------
-- 1. Tabel
-- ---------------------------------------------------------------------------

-- 1.1 profiles : pengguna aplikasi, 1:1 dengan auth.users
create table if not exists public.profiles (
  id          uuid primary key references auth.users(id) on delete cascade,
  username    text not null unique check (username = lower(username) and username ~ '^[a-z0-9._-]{3,30}$'),
  full_name   text not null check (length(btrim(full_name)) between 2 and 100),
  role        text not null default 'Karyawan' check (role in ('Admin','Karyawan')),
  legacy_id   int,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now()
);

comment on table  public.profiles is 'Pengguna JoyOps. Password tidak di sini, ditangani Supabase Auth.';
comment on column public.profiles.username is 'Dipakai untuk login, dipetakan ke <username>@<AUTH_EMAIL_DOMAIN>.';
comment on column public.profiles.legacy_id is 'ID pada tabel users versi PHP, untuk penelusuran migrasi.';

-- 1.2 machines : mesin cuci dan pengering
create table if not exists public.machines (
  id            bigint generated by default as identity primary key,
  machine_code  text not null unique check (machine_code ~ '^[A-Z]{2}-[0-9]{2,3}$'),
  machine_type  text not null,
  status        text not null default 'Tersedia' check (status in ('Tersedia','Digunakan','Maintenance')),
  last_used     timestamptz,
  available_at  timestamptz,
  created_at    timestamptz not null default now()
);

comment on column public.machines.machine_code is 'Awalan WM- untuk mesin cuci, DM- untuk mesin pengering.';
comment on column public.machines.available_at is 'Perkiraan mesin bebas, diisi dari end_time order yang sedang berjalan.';

-- 1.3 services : layanan laundry
create table if not exists public.services (
  id                bigint generated by default as identity primary key,
  service_name      text not null check (length(btrim(service_name)) between 2 and 100),
  price             numeric(12,2) not null check (price >= 0),
  unit              text not null default 'kg' check (unit in ('kg','pcs')),
  duration_minutes  int  not null default 90 check (duration_minutes >= 1),
  icon              text not null default 'local_laundry_service',
  is_active         boolean not null default true,
  created_at        timestamptz not null default now()
);

comment on column public.services.unit is 'Satuan qty pada order: kg untuk kiloan, pcs untuk satuan.';
comment on column public.services.duration_minutes is 'Durasi standar pengerjaan. Disalin ke order saat order dibuat.';

-- 1.4 addons : layanan tambahan
create table if not exists public.addons (
  id          bigint generated by default as identity primary key,
  addon_name  text not null check (length(btrim(addon_name)) between 2 and 100),
  price       numeric(12,2) not null default 0 check (price >= 0),
  icon        text not null default 'add_circle',
  is_active   boolean not null default true,
  created_at  timestamptz not null default now()
);

-- 1.5 orders : order pelanggan
create table if not exists public.orders (
  id                 bigint generated by default as identity primary key,
  order_code         text not null unique,
  washer_machine_id  bigint not null references public.machines(id) on delete restrict,
  dryer_machine_id   bigint not null references public.machines(id) on delete restrict,
  service_id         bigint not null references public.services(id) on delete restrict,
  customer_name      text not null default 'Walk-in' check (length(btrim(customer_name)) between 1 and 100),
  qty                numeric(10,2) not null default 1 check (qty > 0),
  service_price      numeric(14,2) not null default 0 check (service_price >= 0),
  addon_total        numeric(14,2) not null default 0 check (addon_total >= 0),
  grand_total        numeric(14,2) not null default 0 check (grand_total >= 0),
  duration_minutes   int  not null default 90 check (duration_minutes >= 1),
  start_time         timestamptz not null default now(),
  end_time           timestamptz not null,
  status             text not null default 'Berjalan' check (status in ('Berjalan','Selesai','Dibatalkan')),
  payment_method     text not null default 'Cash' check (payment_method in ('Cash','QRIS')),
  notes              text,
  created_by         uuid not null references public.profiles(id) on delete restrict,
  created_at         timestamptz not null default now(),
  constraint order_mesin_harus_beda check (washer_machine_id <> dryer_machine_id),
  constraint order_waktu_wajar      check (end_time > start_time)
);

comment on column public.orders.washer_machine_id is 'Mesin cuci. Wajib, BR-01.';
comment on column public.orders.dryer_machine_id  is 'Mesin pengering. Wajib, BR-01.';

-- 1.6 order_addons : add-on per order (harga disalin, BR-08)
create table if not exists public.order_addons (
  id          bigint generated by default as identity primary key,
  order_id    bigint not null references public.orders(id) on delete cascade,
  addon_id    bigint not null references public.addons(id) on delete restrict,
  addon_name  text not null,
  qty         numeric(10,2) not null default 1 check (qty > 0),
  price       numeric(12,2) not null default 0 check (price >= 0),
  subtotal    numeric(14,2) not null default 0 check (subtotal >= 0),
  unique (order_id, addon_id)
);

-- 1.7 transactions : buku kas
create table if not exists public.transactions (
  id                bigint generated by default as identity primary key,
  transaction_date  date not null default ((now() at time zone 'Asia/Jakarta')::date),
  transaction_type  text not null check (transaction_type in ('Pemasukan','Pengeluaran')),
  amount            numeric(14,2) not null check (amount >= 0),
  payment_method    text not null default 'Cash' check (payment_method in ('Cash','QRIS','Transfer')),
  description       text,
  order_id          bigint unique references public.orders(id) on delete cascade,
  created_by        uuid references public.profiles(id) on delete set null,
  created_at        timestamptz not null default now()
);

comment on column public.transactions.order_id is 'Terisi kalau pemasukan berasal dari order. Unik, mencegah pemasukan dobel.';

-- 1.8 shifts : jadwal terwujud
create table if not exists public.shifts (
  id          bigint generated by default as identity primary key,
  profile_id  uuid not null references public.profiles(id) on delete cascade,
  work_day    text not null check (work_day in ('Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday')),
  work_date   date not null,
  start_time  time not null,
  end_time    time not null,
  station     text not null,
  status      text not null default 'Scheduled' check (status in ('Scheduled','Clocked In','Completed')),
  created_at  timestamptz not null default now(),
  constraint shift_jam_wajar check (end_time > start_time),
  constraint shift_tidak_tumpang_tindih unique (profile_id, work_date, start_time)
);

comment on constraint shift_tidak_tumpang_tindih on public.shifts is 'BR-14: satu orang tidak boleh punya dua shift mulai di jam yang sama.';

-- 1.9 shift_templates : pola shift berulang
create table if not exists public.shift_templates (
  id           bigint generated by default as identity primary key,
  profile_id   uuid not null references public.profiles(id) on delete cascade,
  day_of_week  text not null check (day_of_week in ('Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday')),
  shift_type   text not null check (shift_type in ('Shift 1','Shift 2')),
  station      text not null,
  is_active    boolean not null default true,
  created_at   timestamptz not null default now(),
  unique (profile_id, day_of_week, shift_type)
);

-- 1.10 shift_swap_requests : pengajuan tukar shift
create table if not exists public.shift_swap_requests (
  id                  bigint generated by default as identity primary key,
  shift_id            bigint not null references public.shifts(id) on delete cascade,
  requester_id        uuid not null references public.profiles(id) on delete cascade,
  target_shift_id     bigint not null references public.shifts(id) on delete cascade,
  target_employee_id  uuid not null references public.profiles(id) on delete cascade,
  status              text not null default 'Pending'
                      check (status in ('Pending','Accepted by Employee','Rejected by Employee','Approved','Rejected by Admin')),
  accepter_id         uuid references public.profiles(id) on delete set null,
  decided_by          uuid references public.profiles(id) on delete set null,
  decided_at          timestamptz,
  created_at          timestamptz not null default now(),
  constraint swap_shift_harus_beda check (shift_id <> target_shift_id)
);

-- 1.11 attendance : absensi
create table if not exists public.attendance (
  id           bigint generated by default as identity primary key,
  profile_id   uuid not null references public.profiles(id) on delete cascade,
  shift_id     bigint references public.shifts(id) on delete set null,
  work_date    date not null default ((now() at time zone 'Asia/Jakarta')::date),
  clock_in     timestamptz,
  clock_out    timestamptz,
  status       text not null default 'Pending' check (status in ('Pending','Approved','Rejected')),
  approved_by  uuid references public.profiles(id) on delete set null,
  notes        text,
  created_at   timestamptz not null default now(),
  constraint attendance_satu_per_hari unique (profile_id, work_date),
  constraint attendance_jam_wajar check (clock_out is null or clock_in is null or clock_out > clock_in)
);

-- 1.12 notifications : notifikasi per penerima (fan-out saat insert)
create table if not exists public.notifications (
  id            bigint generated by default as identity primary key,
  user_id       uuid not null references public.profiles(id) on delete cascade,
  title         text not null,
  message       text not null,
  type          text not null default 'info' check (type in ('info','success','warning','error')),
  related_type  text,
  related_id    bigint,
  is_read       boolean not null default false,
  created_at    timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- 2. Indeks
-- ---------------------------------------------------------------------------
create index if not exists idx_orders_status_end      on public.orders (status, end_time);
create index if not exists idx_orders_created_at      on public.orders (created_at desc);
create index if not exists idx_orders_washer          on public.orders (washer_machine_id);
create index if not exists idx_orders_dryer           on public.orders (dryer_machine_id);
create index if not exists idx_transactions_tanggal   on public.transactions (transaction_date desc);
create index if not exists idx_transactions_tipe      on public.transactions (transaction_type, transaction_date desc);
create index if not exists idx_shifts_tanggal         on public.shifts (work_date, profile_id);
create index if not exists idx_shifts_orang           on public.shifts (profile_id, work_date);
create index if not exists idx_attendance_orang       on public.attendance (profile_id, work_date desc);
create index if not exists idx_notif_penerima         on public.notifications (user_id, is_read, created_at desc);
create index if not exists idx_swap_status            on public.shift_swap_requests (status, created_at desc);
create index if not exists idx_order_addons_order     on public.order_addons (order_id);

-- ---------------------------------------------------------------------------
-- 3. Fungsi bantu
-- ---------------------------------------------------------------------------

-- 3.1 Peran pengguna yang sedang login
create or replace function public.peran_saya()
returns text
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select role from public.profiles where id = auth.uid()
$$;

-- 3.2 Apakah pengguna yang login seorang Admin
create or replace function public.adminkah()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select coalesce((select role from public.profiles where id = auth.uid()) = 'Admin', false)
$$;

-- 3.3 Kirim notifikasi, fan-out ke penerima yang tepat
create or replace function public.notify(
  p_title         text,
  p_message       text,
  p_type          text default 'info',
  p_for_role      text default 'All',
  p_user_id       uuid default null,
  p_related_type  text default null,
  p_related_id    bigint default null
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if p_user_id is not null then
    insert into public.notifications (user_id, title, message, type, related_type, related_id)
    values (p_user_id, p_title, p_message, p_type, p_related_type, p_related_id);
    return;
  end if;

  insert into public.notifications (user_id, title, message, type, related_type, related_id)
  select p.id, p_title, p_message, p_type, p_related_type, p_related_id
    from public.profiles p
   where p.is_active
     and (p_for_role is null or p_for_role = 'All' or p.role = p_for_role);
end;
$$;

-- 3.4 Lepaskan mesin yang tidak lagi dipakai order berjalan
create or replace function public.lepaskan_mesin_bebas()
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  update public.machines m
     set status = 'Tersedia',
         available_at = null
   where m.status = 'Digunakan'
     and not exists (
       select 1
         from public.orders o
        where o.status = 'Berjalan'
          and (o.washer_machine_id = m.id or o.dryer_machine_id = m.id)
     );
end;
$$;

-- 3.5 Tutup order yang sudah lewat end_time (pengganti "Order Otomatis Selesai")
create or replace function public.tutup_order_kedaluwarsa()
returns int
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_jumlah int;
begin
  with ditutup as (
    update public.orders
       set status = 'Selesai'
     where status = 'Berjalan'
       and end_time <= now()
    returning id, order_code
  )
  select count(*) into v_jumlah from ditutup;

  if v_jumlah > 0 then
    perform public.lepaskan_mesin_bebas();

    insert into public.notifications (user_id, title, message, type, related_type)
    select p.id, 'Order Otomatis Selesai',
           v_jumlah || ' order ditutup otomatis karena waktunya habis.', 'info', 'order'
      from public.profiles p
     where p.is_active;
  end if;

  return v_jumlah;
end;
$$;

-- 3.6 Ubah nama profil sendiri (tanpa izin mengubah peran)
create or replace function public.ubah_profil_saya(p_full_name text)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if p_full_name is null or length(btrim(p_full_name)) < 2 then
    raise exception 'Nama minimal 2 karakter' using errcode = '22023';
  end if;

  update public.profiles
     set full_name = btrim(p_full_name)
   where id = auth.uid();
end;
$$;

-- ---------------------------------------------------------------------------
-- 4. Fungsi inti: buat order, selesaikan order, batalkan order
--    Dijalankan sebagai security definer supaya:
--      a. status mesin bisa diubah walau karyawan tidak punya izin tulis mesin
--      b. seluruh langkah jadi satu transaksi, tidak ada data separuh jadi
--      c. dua order tidak bisa merebut mesin yang sama (row lock)
-- ---------------------------------------------------------------------------

-- 4.1 Buat order
create or replace function public.buat_order(
  p_washer_id       bigint,
  p_dryer_id        bigint,
  p_service_id      bigint,
  p_customer_name   text,
  p_qty             numeric,
  p_addon_ids       bigint[] default '{}',
  p_payment_method  text default 'Cash',
  p_notes           text default null
)
returns public.orders
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_saya      uuid := auth.uid();
  v_wm        public.machines;
  v_dm        public.machines;
  v_layanan   public.services;
  v_order     public.orders;
  v_qty       numeric(10,2);
  v_svc_total numeric(14,2);
  v_add_total numeric(14,2) := 0;
  v_durasi    int;
  v_kode      text;
begin
  if v_saya is null then
    raise exception 'Sesi tidak ditemukan' using errcode = '28000';
  end if;

  if not exists (select 1 from public.profiles where id = v_saya and is_active) then
    raise exception 'Akun tidak aktif' using errcode = '28000';
  end if;

  v_qty := round(coalesce(p_qty, 0), 2);
  if v_qty <= 0 then
    raise exception 'Qty harus lebih dari 0' using errcode = '22023';
  end if;

  if p_payment_method not in ('Cash','QRIS') then
    raise exception 'Metode pembayaran tidak dikenal' using errcode = '22023';
  end if;

  -- Kunci kedua mesin. Kunci baris mencegah dua order merebut mesin yang sama.
  select * into v_wm from public.machines where id = p_washer_id for update;
  if not found then
    raise exception 'Mesin cuci tidak ditemukan' using errcode = '22023';
  end if;

  select * into v_dm from public.machines where id = p_dryer_id for update;
  if not found then
    raise exception 'Mesin pengering tidak ditemukan' using errcode = '22023';
  end if;

  if v_wm.id = v_dm.id then
    raise exception 'Mesin cuci dan pengering harus berbeda' using errcode = '22023';
  end if;

  if v_wm.machine_code not like 'WM-%' then
    raise exception 'Mesin % bukan mesin cuci', v_wm.machine_code using errcode = '22023';
  end if;

  if v_dm.machine_code not like 'DM-%' then
    raise exception 'Mesin % bukan mesin pengering', v_dm.machine_code using errcode = '22023';
  end if;

  if v_wm.status <> 'Tersedia' then
    raise exception 'Mesin % sedang tidak tersedia', v_wm.machine_code using errcode = '22023';
  end if;

  if v_dm.status <> 'Tersedia' then
    raise exception 'Mesin % sedang tidak tersedia', v_dm.machine_code using errcode = '22023';
  end if;

  select * into v_layanan from public.services where id = p_service_id and is_active;
  if not found then
    raise exception 'Layanan tidak ditemukan atau tidak aktif' using errcode = '22023';
  end if;

  v_durasi := greatest(coalesce(v_layanan.duration_minutes, 90), 1);  -- BR-05
  v_svc_total := round(v_layanan.price * v_qty, 2);

  -- Kode order: ORD-YYYYMMDD-NNNN, urut per hari
  v_kode := 'ORD-' || to_char(now() at time zone 'Asia/Jakarta', 'YYYYMMDD') || '-' ||
            lpad((
              select coalesce(count(*), 0) + 1
                from public.orders o
               where (o.created_at at time zone 'Asia/Jakarta')::date
                     = (now() at time zone 'Asia/Jakarta')::date
            )::text, 4, '0');

  insert into public.orders (
    order_code, washer_machine_id, dryer_machine_id, service_id,
    customer_name, qty, service_price, addon_total, grand_total,
    duration_minutes, start_time, end_time, status, payment_method, notes, created_by
  ) values (
    v_kode, v_wm.id, v_dm.id, v_layanan.id,
    coalesce(nullif(btrim(p_customer_name), ''), 'Walk-in'), v_qty, v_svc_total, 0, v_svc_total,
    v_durasi, now(), now() + make_interval(mins => v_durasi),
    'Berjalan', p_payment_method, nullif(btrim(coalesce(p_notes, '')), ''), v_saya
  )
  returning * into v_order;

  -- Add-on. Harga dan nama disalin ke baris order (BR-08).
  if p_addon_ids is not null and array_length(p_addon_ids, 1) > 0 then
    insert into public.order_addons (order_id, addon_id, addon_name, qty, price, subtotal)
    select v_order.id, a.id, a.addon_name, 1, a.price, round(a.price * 1, 2)
      from public.addons a
     where a.id = any(p_addon_ids)
       and a.is_active;

    select coalesce(sum(oa.subtotal), 0) into v_add_total
      from public.order_addons oa
     where oa.order_id = v_order.id;
  end if;

  -- Total akhir dihitung di server (BR-06)
  update public.orders
     set addon_total = v_add_total,
         grand_total = round(v_svc_total + v_add_total, 2)
   where id = v_order.id
  returning * into v_order;

  -- Mesin dipakai (BR-07)
  update public.machines
     set status = 'Digunakan',
         last_used = now(),
         available_at = v_order.end_time
   where id in (v_wm.id, v_dm.id);

  -- Pemasukan otomatis
  insert into public.transactions (transaction_date, transaction_type, amount, payment_method, description, order_id, created_by)
  values (
    (now() at time zone 'Asia/Jakarta')::date,
    'Pemasukan',
    v_order.grand_total,
    v_order.payment_method,
    'Order ' || v_order.order_code || ' - ' || v_wm.machine_code || ' & ' || v_dm.machine_code ||
      ' - ' || v_layanan.service_name || ' (' || trim(to_char(v_qty, 'FM999999990.##')) || ' ' || v_layanan.unit || ')',
    v_order.id,
    v_saya
  )
  on conflict (order_id) do nothing;

  perform public.notify(
    'Order Baru',
    'Order ' || v_order.order_code || ' untuk ' || v_wm.machine_code || ' & ' || v_dm.machine_code ||
      ' - ' || v_order.customer_name || '. Total: Rp ' ||
      to_char(v_order.grand_total, 'FM999,999,999'),
    'success', 'All', null, 'order', v_order.id
  );

  return v_order;
end;
$$;

-- 4.2 Selesaikan order
create or replace function public.selesaikan_order(p_order_id bigint)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_order public.orders;
begin
  if auth.uid() is null then
    raise exception 'Sesi tidak ditemukan' using errcode = '28000';
  end if;

  select * into v_order from public.orders where id = p_order_id for update;
  if not found then
    raise exception 'Order tidak ditemukan' using errcode = '22023';
  end if;

  if v_order.status <> 'Berjalan' then
    raise exception 'Order % sudah tidak berjalan', v_order.order_code using errcode = '22023';
  end if;

  update public.orders set status = 'Selesai' where id = p_order_id;
  perform public.lepaskan_mesin_bebas();

  perform public.notify(
    'Order Selesai',
    'Order ' || v_order.order_code || ' telah selesai. Mesin kembali tersedia.',
    'info', 'All', null, 'order', p_order_id
  );
end;
$$;

-- 4.3 Batalkan order (Admin saja)
create or replace function public.batalkan_order(p_order_id bigint, p_alasan text default null)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_order public.orders;
begin
  if not public.adminkah() then
    raise exception 'Hanya Admin yang boleh membatalkan order' using errcode = '42501';
  end if;

  select * into v_order from public.orders where id = p_order_id for update;
  if not found then
    raise exception 'Order tidak ditemukan' using errcode = '22023';
  end if;

  if v_order.status = 'Dibatalkan' then
    return;
  end if;

  update public.orders
     set status = 'Dibatalkan',
         notes = coalesce(nullif(btrim(p_alasan), ''), notes)
   where id = p_order_id;

  -- Pemasukan order batal tidak boleh ikut terhitung
  delete from public.transactions where order_id = p_order_id;

  perform public.lepaskan_mesin_bebas();

  perform public.notify(
    'Order Dibatalkan',
    'Order ' || v_order.order_code || ' dibatalkan.' ||
      case when p_alasan is null or btrim(p_alasan) = '' then '' else ' Alasan: ' || p_alasan end,
    'warning', 'All', null, 'order', p_order_id
  );
end;
$$;

-- 4.4 Setujui tukar shift (Admin). Menukar pemilik kedua shift.
create or replace function public.setujui_tukar_shift(p_permintaan_id bigint, p_setuju boolean)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_req    public.shift_swap_requests;
  v_shift  public.shifts;
  v_target public.shifts;
  v_status text;
begin
  if not public.adminkah() then
    raise exception 'Hanya Admin yang boleh menyetujui tukar shift' using errcode = '42501';
  end if;

  select * into v_req from public.shift_swap_requests where id = p_permintaan_id for update;
  if not found then
    raise exception 'Pengajuan tidak ditemukan' using errcode = '22023';
  end if;

  if v_req.status <> 'Accepted by Employee' then
    raise exception 'Pengajuan belum diterima rekan kerja' using errcode = '22023';
  end if;

  if p_setuju then
    select * into v_shift  from public.shifts where id = v_req.shift_id        for update;
    select * into v_target from public.shifts where id = v_req.target_shift_id for update;

    if v_shift.id is null or v_target.id is null then
      raise exception 'Shift sudah tidak ada' using errcode = '22023';
    end if;

    update public.shifts set profile_id = v_target.profile_id where id = v_shift.id;
    update public.shifts set profile_id = v_shift.profile_id  where id = v_target.id;

    v_status := 'Approved';

    perform public.notify('Tukar Shift Disetujui',
      'Tukar shift ' || v_shift.work_date || ' disetujui Admin. Jadwal sudah diperbarui.',
      'success', 'All', null, 'shift_swap', p_permintaan_id);
  else
    v_status := 'Rejected by Admin';

    perform public.notify('Tukar Shift Ditolak',
      'Tukar shift ditolak Admin. Jadwal tidak berubah.',
      'warning', 'All', null, 'shift_swap', p_permintaan_id);
  end if;

  update public.shift_swap_requests
     set status = v_status,
         decided_by = auth.uid(),
         decided_at = now()
   where id = p_permintaan_id;
end;
$$;

-- 4.5 Clock in / clock out
create or replace function public.absen_masuk(p_shift_id bigint default null)
returns public.attendance
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_saya   uuid := auth.uid();
  v_hasil  public.attendance;
  v_tanggal date := (now() at time zone 'Asia/Jakarta')::date;
begin
  if v_saya is null then
    raise exception 'Sesi tidak ditemukan' using errcode = '28000';
  end if;

  insert into public.attendance (profile_id, shift_id, work_date, clock_in, status)
  values (v_saya, p_shift_id, v_tanggal, now(), 'Pending')
  on conflict (profile_id, work_date) do update
     set clock_in = coalesce(public.attendance.clock_in, now()),
         shift_id = coalesce(public.attendance.shift_id, excluded.shift_id)
  returning * into v_hasil;

  if p_shift_id is not null then
    update public.shifts set status = 'Clocked In' where id = p_shift_id;
  end if;

  perform public.notify('Absen Masuk',
    'Seorang karyawan melakukan clock in.', 'info', 'Admin', null, 'attendance', v_hasil.id);

  return v_hasil;
end;
$$;

create or replace function public.absen_keluar()
returns public.attendance
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_saya   uuid := auth.uid();
  v_hasil  public.attendance;
  v_tanggal date := (now() at time zone 'Asia/Jakarta')::date;
begin
  if v_saya is null then
    raise exception 'Sesi tidak ditemukan' using errcode = '28000';
  end if;

  update public.attendance
     set clock_out = now()
   where profile_id = v_saya and work_date = v_tanggal
  returning * into v_hasil;

  if v_hasil.id is null then
    raise exception 'Belum ada absen masuk hari ini' using errcode = '22023';
  end if;

  update public.shifts
     set status = 'Completed'
   where id = v_hasil.shift_id;

  return v_hasil;
end;
$$;

-- ---------------------------------------------------------------------------
-- 5. Trigger: profil otomatis saat akun auth dibuat
-- ---------------------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_username text;
  v_nama     text;
  v_peran    text;
begin
  v_username := lower(coalesce(
    nullif(new.raw_user_meta_data->>'username', ''),
    split_part(new.email, '@', 1)
  ));
  v_nama  := coalesce(nullif(new.raw_user_meta_data->>'full_name', ''), initcap(v_username));
  v_peran := coalesce(nullif(new.raw_user_meta_data->>'role', ''), 'Karyawan');

  if v_peran not in ('Admin','Karyawan') then
    v_peran := 'Karyawan';
  end if;

  insert into public.profiles (id, username, full_name, role, legacy_id)
  values (
    new.id,
    v_username,
    v_nama,
    v_peran,
    nullif(new.raw_user_meta_data->>'legacy_id', '')::int
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------------
-- 6. Row Level Security
--    Prinsip: gagal-tertutup. Tabel tanpa policy = ditolak.
-- ---------------------------------------------------------------------------
alter table public.profiles             enable row level security;
alter table public.machines             enable row level security;
alter table public.services             enable row level security;
alter table public.addons               enable row level security;
alter table public.orders               enable row level security;
alter table public.order_addons         enable row level security;
alter table public.transactions         enable row level security;
alter table public.shifts               enable row level security;
alter table public.shift_templates      enable row level security;
alter table public.shift_swap_requests  enable row level security;
alter table public.attendance           enable row level security;
alter table public.notifications        enable row level security;

-- 6.1 profiles
-- Baca: seluruh karyawan yang sudah masuk boleh melihat daftar rekan kerjanya.
-- Alasannya: daftar ini dipakai di layar kerja, yaitu kolom Kasir pada tabel
-- order dan nama rekan pada pengajuan tukar shift. Isi tabel ini hanya
-- identitas kerja (nama, username, peran, status aktif), tidak ada bahan
-- rahasia. Sandi ada di auth.users, bukan di sini.
-- Tulis: tetap hanya Admin, jadi peran tidak bisa dinaikkan sendiri.
drop policy if exists profiles_baca on public.profiles;
create policy profiles_baca on public.profiles
  for select to authenticated
  using (true);

drop policy if exists profiles_tulis_admin on public.profiles;
create policy profiles_tulis_admin on public.profiles
  for all to authenticated
  using (public.adminkah())
  with check (public.adminkah());
-- Ubah nama sendiri lewat fungsi ubah_profil_saya(), bukan lewat update langsung,
-- supaya kolom role tidak bisa dinaikkan sendiri.

-- 6.2 machines : semua boleh baca, hanya Admin boleh tulis
drop policy if exists machines_baca on public.machines;
create policy machines_baca on public.machines
  for select to authenticated using (true);

drop policy if exists machines_tulis on public.machines;
create policy machines_tulis on public.machines
  for all to authenticated
  using (public.adminkah())
  with check (public.adminkah());

-- 6.3 services
drop policy if exists services_baca on public.services;
create policy services_baca on public.services
  for select to authenticated using (true);

drop policy if exists services_tulis on public.services;
create policy services_tulis on public.services
  for all to authenticated
  using (public.adminkah())
  with check (public.adminkah());

-- 6.4 addons
drop policy if exists addons_baca on public.addons;
create policy addons_baca on public.addons
  for select to authenticated using (true);

drop policy if exists addons_tulis on public.addons;
create policy addons_tulis on public.addons
  for all to authenticated
  using (public.adminkah())
  with check (public.adminkah());

-- 6.5 orders : baca semua, tulis lewat fungsi, Admin boleh koreksi
drop policy if exists orders_baca on public.orders;
create policy orders_baca on public.orders
  for select to authenticated using (true);

drop policy if exists orders_ubah_admin on public.orders;
create policy orders_ubah_admin on public.orders
  for update to authenticated
  using (public.adminkah())
  with check (public.adminkah());

drop policy if exists orders_hapus_admin on public.orders;
create policy orders_hapus_admin on public.orders
  for delete to authenticated
  using (public.adminkah());
-- Insert tidak diberi policy: order hanya lahir dari fungsi buat_order().

-- 6.6 order_addons
drop policy if exists order_addons_baca on public.order_addons;
create policy order_addons_baca on public.order_addons
  for select to authenticated using (true);

drop policy if exists order_addons_tulis_admin on public.order_addons;
create policy order_addons_tulis_admin on public.order_addons
  for all to authenticated
  using (public.adminkah())
  with check (public.adminkah());

-- 6.7 transactions : hanya Admin (BR-13)
drop policy if exists transactions_admin on public.transactions;
create policy transactions_admin on public.transactions
  for all to authenticated
  using (public.adminkah())
  with check (public.adminkah());

-- 6.8 shifts
drop policy if exists shifts_baca on public.shifts;
create policy shifts_baca on public.shifts
  for select to authenticated using (true);

drop policy if exists shifts_tulis on public.shifts;
create policy shifts_tulis on public.shifts
  for all to authenticated
  using (public.adminkah())
  with check (public.adminkah());

-- 6.9 shift_templates
drop policy if exists templates_baca on public.shift_templates;
create policy templates_baca on public.shift_templates
  for select to authenticated using (true);

drop policy if exists templates_tulis on public.shift_templates;
create policy templates_tulis on public.shift_templates
  for all to authenticated
  using (public.adminkah())
  with check (public.adminkah());

-- 6.10 shift_swap_requests
drop policy if exists swap_baca on public.shift_swap_requests;
create policy swap_baca on public.shift_swap_requests
  for select to authenticated using (true);

drop policy if exists swap_ajukan on public.shift_swap_requests;
create policy swap_ajukan on public.shift_swap_requests
  for insert to authenticated
  with check (requester_id = auth.uid() and status = 'Pending');

drop policy if exists swap_jawab on public.shift_swap_requests;
create policy swap_jawab on public.shift_swap_requests
  for update to authenticated
  using (
    public.adminkah()
    or target_employee_id = auth.uid()
    or requester_id = auth.uid()
  )
  with check (
    public.adminkah()
    or target_employee_id = auth.uid()
    or requester_id = auth.uid()
  );

-- 6.11 attendance
drop policy if exists attendance_baca on public.attendance;
create policy attendance_baca on public.attendance
  for select to authenticated
  using (profile_id = auth.uid() or public.adminkah());

drop policy if exists attendance_tulis_admin on public.attendance;
create policy attendance_tulis_admin on public.attendance
  for update to authenticated
  using (public.adminkah())
  with check (public.adminkah());
-- Insert absen lewat fungsi absen_masuk().

-- 6.12 notifications : hanya milik sendiri
drop policy if exists notif_baca on public.notifications;
create policy notif_baca on public.notifications
  for select to authenticated
  using (user_id = auth.uid());

drop policy if exists notif_tandai on public.notifications;
create policy notif_tandai on public.notifications
  for update to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- ---------------------------------------------------------------------------
-- 7. Hak akses
-- ---------------------------------------------------------------------------
grant usage on schema public to anon, authenticated;

grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;

revoke all on all tables in schema public from anon;

-- Fungsi publik yang boleh dipanggil pengguna yang sudah masuk
grant execute on function public.buat_order(bigint,bigint,bigint,text,numeric,bigint[],text,text) to authenticated;
grant execute on function public.selesaikan_order(bigint)        to authenticated;
grant execute on function public.batalkan_order(bigint,text)     to authenticated;
grant execute on function public.absen_masuk(bigint)             to authenticated;
grant execute on function public.absen_keluar()                  to authenticated;
grant execute on function public.ubah_profil_saya(text)          to authenticated;
grant execute on function public.setujui_tukar_shift(bigint,boolean) to authenticated;
grant execute on function public.notify(text,text,text,text,uuid,text,bigint) to authenticated;
grant execute on function public.tutup_order_kedaluwarsa()       to authenticated;
grant execute on function public.peran_saya()                    to authenticated;
grant execute on function public.adminkah()                      to authenticated;

-- Fungsi internal tidak dipanggil dari klien
revoke execute on function public.lepaskan_mesin_bebas() from anon, authenticated, public;

-- ---------------------------------------------------------------------------
-- 8. Pemeriksaan
-- ---------------------------------------------------------------------------
do $$
declare
  v_tabel int;
  v_rls   int;
  v_pol   int;
begin
  select count(*) into v_tabel
    from information_schema.tables
   where table_schema = 'public' and table_type = 'BASE TABLE';

  select count(*) into v_rls
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'public' and c.relkind = 'r' and c.relrowsecurity;

  select count(*) into v_pol
    from pg_policies
   where schemaname = 'public';

  raise notice 'JoyOps: % tabel, % dengan RLS, % policy', v_tabel, v_rls, v_pol;

  if v_tabel <> 12 then
    raise warning 'Harapannya 12 tabel, terbaca %', v_tabel;
  end if;

  if v_rls <> v_tabel then
    raise warning 'Ada tabel tanpa RLS. Itu bug, bukan pilihan.';
  end if;
end $$;
