-- ============================================================================
-- JoyOps v3 : Perbaikan alur cucian dan pelunasan nota
--
-- Jalankan lewat SQL Editor Supabase, SETELAH 01_schema.sql dan 02_seed.sql.
-- Sifatnya menambah saja: tidak menghapus kolom, tidak mengubah isi tabel yang
-- sudah ada, jadi aman dijalankan pada database yang sudah berisi order.
--
-- Yang ditambahkan:
--   1. Status order diperluas mengikuti alur pencucian sampai pengambilan
--   2. racks : rak simpan
--   3. orders : rak, janji selesai, berat akhir, pelunasan, jejak pembatalan
--   4. machines : kapasitas muat
--   5. transactions : pelunasan boleh lebih dari satu baris per order
--   6. Fungsi tandai_siap_ambil dan lunasi_order
--   7. Indeks pendukung
--
-- CATATAN PENTING soal Pemasukan.
-- Selama ini public.buat_order (01_schema.sql baris 482 sampai 495) langsung
-- mencatat Pemasukan sebesar grand_total saat order dibuat. Setelah file ini
-- dijalankan, uang seharusnya dicatat saat pelunasan lewat public.lunasi_order.
-- Kalau keduanya jalan, kas Anda terhitung dua kali. Jadi: setelah menjalankan
-- file ini, hapus blok "Pemasukan otomatis" di dalam buat_order. Perubahan itu
-- sengaja tidak disertakan di sini supaya Anda bisa menguji satu langkah dulu.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. Status order
-- 'Berjalan' dan 'Selesai' tetap dipertahankan supaya UI versi sekarang masih
-- jalan sebelum ikut diperbarui. Rantai yang dituju:
--     Antre -> Dicuci -> Dikeringkan -> Disetrika -> Siap Ambil -> Sudah Diambil
-- dan Dibatalkan dari titik mana pun.
-- ---------------------------------------------------------------------------
alter table public.orders drop constraint if exists orders_status_check;

alter table public.orders
  add constraint orders_status_check check (
    status in (
      'Berjalan','Antre','Dicuci','Dikeringkan','Disetrika',
      'Siap Ambil','Sudah Diambil','Selesai','Dibatalkan'
    )
  );

-- ---------------------------------------------------------------------------
-- 2. racks : rak simpan
-- Tanpa kode rak, cucian yang sudah selesai tidak bisa ditemukan kembali saat
-- pelanggan datang. Kolom note dipakai untuk lokasi fisik, misalnya "dekat kasir".
-- ---------------------------------------------------------------------------
create table if not exists public.racks (
  id          bigint generated by default as identity primary key,
  rack_code   text not null unique check (rack_code ~ '^R-[0-9]{2,3}$'),
  capacity    int  not null default 10 check (capacity > 0),
  note        text,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now()
);

comment on column public.racks.rack_code is 'Kode rak, pola R-01. Ditempel di rak fisiknya.';
comment on column public.racks.capacity is 'Jumlah maksimal kantong per rak. Dipakai untuk memperingatkan rak penuh.';

alter table public.racks enable row level security;

drop policy if exists racks_baca on public.racks;
create policy racks_baca on public.racks
  for select to authenticated
  using (true);

drop policy if exists racks_tulis on public.racks;
create policy racks_tulis on public.racks
  for all to authenticated
  using (public.adminkah())
  with check (public.adminkah());

-- ---------------------------------------------------------------------------
-- 3. orders : kolom yang kurang
-- ---------------------------------------------------------------------------
alter table public.orders
  add column if not exists rack_id          bigint references public.racks(id) on delete set null,
  add column if not exists stored_at        timestamptz,
  add column if not exists pickup_due       timestamptz,
  add column if not exists promised_done_at timestamptz,
  add column if not exists qty_final        numeric(10,2) check (qty_final is null or qty_final > 0),
  add column if not exists is_express       boolean not null default false,
  add column if not exists express_fee      numeric(14,2) not null default 0 check (express_fee >= 0),
  add column if not exists payment_status   text not null default 'Belum Lunas'
                                            check (payment_status in ('Belum Lunas','DP','Lunas')),
  add column if not exists paid_amount      numeric(14,2) not null default 0 check (paid_amount >= 0),
  add column if not exists paid_at          timestamptz,
  add column if not exists cancelled_at     timestamptz,
  add column if not exists cancelled_by     uuid references public.profiles(id) on delete set null,
  add column if not exists cancel_reason    text;

comment on column public.orders.qty_final is 'Hasil timbang akhir. Diisi kalau berbeda dari qty saat penerimaan.';
comment on column public.orders.promised_done_at is 'Janji selesai ke pelanggan. Beda dari end_time yang hanya menandai mesin bebas.';
comment on column public.orders.pickup_due is 'Batas waktu pengambilan. Setelah ini cucian boleh dikenai biaya simpan.';
comment on column public.orders.cancel_reason is 'Alasan pembatalan. Semula ditulis ke notes sehingga catatan asli tertimpa.';

-- ---------------------------------------------------------------------------
-- 4. machines : kapasitas
-- Tanpa kapasitas, sistem tidak bisa menyarankan mesin untuk beban 7 kg atau
-- memperingatkan mesin kelebihan muat.
-- ---------------------------------------------------------------------------
alter table public.machines
  add column if not exists capacity_kg numeric(5,2) check (capacity_kg is null or capacity_kg > 0);

comment on column public.machines.capacity_kg is 'Kapasitas cuci atau kering dalam kilogram.';

-- ---------------------------------------------------------------------------
-- 5. transactions : pelunasan bertahap
-- order_id semula UNIQUE, sehingga DP lalu pelunasan tidak mungkin dicatat
-- sebagai dua baris. Batas uniknya dilepas, diganti indeks biasa.
-- ---------------------------------------------------------------------------
alter table public.transactions drop constraint if exists transactions_order_id_key;

create index if not exists idx_transactions_order on public.transactions (order_id);

-- ---------------------------------------------------------------------------
-- 6. Fungsi
-- ---------------------------------------------------------------------------

-- 6.1 Tandai cucian siap diambil dan titipkan ke rak
create or replace function public.tandai_siap_ambil(
  p_order_id bigint,
  p_rack_id  bigint default null
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_order public.orders;
begin
  select * into v_order from public.orders where id = p_order_id for update;
  if not found then
    raise exception 'Order % tidak ditemukan', p_order_id;
  end if;

  if v_order.status in ('Sudah Diambil','Dibatalkan') then
    raise exception 'Order % sudah diambil atau dibatalkan', v_order.order_code;
  end if;

  if p_rack_id is not null and not exists (
    select 1 from public.racks where id = p_rack_id and is_active
  ) then
    raise exception 'Rak % tidak ada atau tidak aktif', p_rack_id;
  end if;

  update public.orders
     set status     = 'Siap Ambil',
         rack_id    = coalesce(p_rack_id, rack_id),
         stored_at  = coalesce(stored_at, now()),
         pickup_due = coalesce(pickup_due, now() + interval '3 days')
   where id = p_order_id;

  perform public.notify(
    'Cucian Siap Ambil',
    'Order ' || v_order.order_code || ' sudah siap diambil.',
    'success', 'All', null, 'order', p_order_id
  );
end;
$$;

comment on function public.tandai_siap_ambil(bigint, bigint) is
  'Set status Siap Ambil, titipkan ke rak, dan tetapkan batas pengambilan 3 hari.';

-- 6.2 Pelunasan nota
-- Boleh dipanggil sebagian untuk DP. Pemasukan dicatat sebesar pembayaran itu
-- saja, jadi buku kas selalu sama dengan uang yang benar-benar diterima.
-- Mengembalikan sisa tagihan setelah pembayaran ini; 0 berarti lunas.
create or replace function public.lunasi_order(
  p_order_id bigint,
  p_jumlah   numeric,
  p_metode   text default 'Cash'
)
returns numeric
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_order public.orders;
  v_sisa  numeric(14,2);
  v_bayar numeric(14,2);
begin
  if p_jumlah is null or p_jumlah <= 0 then
    raise exception 'Jumlah bayar harus lebih dari nol';
  end if;

  if p_metode is null or p_metode not in ('Cash','QRIS','Transfer') then
    raise exception 'Metode bayar % tidak dikenal', coalesce(p_metode, 'kosong');
  end if;

  select * into v_order from public.orders where id = p_order_id for update;
  if not found then
    raise exception 'Order % tidak ditemukan', p_order_id;
  end if;

  if v_order.status = 'Dibatalkan' then
    raise exception 'Order % sudah dibatalkan', v_order.order_code;
  end if;

  v_sisa := v_order.grand_total - v_order.paid_amount;
  if v_sisa <= 0 then
    raise exception 'Order % sudah lunas', v_order.order_code;
  end if;

  v_bayar := least(p_jumlah, v_sisa);

  insert into public.transactions (
    transaction_type, amount, payment_method, description, order_id, created_by
  ) values (
    'Pemasukan', v_bayar, p_metode, 'Pelunasan ' || v_order.order_code, p_order_id, auth.uid()
  );

  update public.orders
     set paid_amount    = paid_amount + v_bayar,
         payment_status = case
                            when paid_amount + v_bayar >= grand_total then 'Lunas'
                            else 'DP'
                          end,
         paid_at        = now()
   where id = p_order_id;

  return v_sisa - v_bayar;
end;
$$;

comment on function public.lunasi_order(bigint, numeric, text) is
  'Catat pembayaran nota, boleh sebagian. Mengembalikan sisa tagihan.';

-- 6.3 Tandai sudah diambil dan kosongkan rak
create or replace function public.cucian_diambil(p_order_id bigint, p_metode text default 'Cash')
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_order public.orders;
begin
  select * into v_order from public.orders where id = p_order_id for update;
  if not found then
    raise exception 'Order % tidak ditemukan', p_order_id;
  end if;

  if v_order.status = 'Dibatalkan' then
    raise exception 'Order % sudah dibatalkan', v_order.order_code;
  end if;

  if v_order.paid_amount < v_order.grand_total then
    raise exception 'Order % belum lunas, sisa %', v_order.order_code,
      to_char(v_order.grand_total - v_order.paid_amount, 'FM999999990.00');
  end if;

  update public.orders
     set status   = 'Sudah Diambil',
         rack_id  = null,
         paid_at  = coalesce(paid_at, now())
   where id = p_order_id;
end;
$$;

comment on function public.cucian_diambil(bigint, text) is
  'Tutup order setelah lunas dan pelanggan mengambil cucian. Mengosongkan rak.';

-- ---------------------------------------------------------------------------
-- 7. Indeks pendukung
-- ---------------------------------------------------------------------------
create index if not exists idx_orders_rak          on public.orders (rack_id);
create index if not exists idx_orders_antar         on public.orders (status, promised_done_at);
create index if not exists idx_orders_pelunasan     on public.orders (payment_status, pickup_due);
