-- JoyOps 05: Batas Isian dan Permintaan Akun
-- Melengkapi 04_alur_cucian_dan_pelunasan.sql
--
-- Bagian 2.1  kolom kapasitas pada mesin
-- Bagian 2.2  tabel permintaan_akun
-- Bagian 2.3  keamanan baris permintaan_akun
-- Bagian 2.4  fungsi putuskan_permintaan
--
-- Jalankan berurutan setelah 01_schema.sql.

begin;

-- ============================================================================
-- 2.1 Kolom kapasitas pada mesins
-- ============================================================================
-- services.unit punya dua jenis (kg dan pcs), sehingga kapasitas mesin juga
-- perlu dua kolom. Satu kolom saja tidak cukup karena satuannya berbeda.

alter table public.machines
  add column if not exists capacity_kg  numeric(6,2) not null default 8
    check (capacity_kg between 5 and 30),
  add column if not exists capacity_pcs int not null default 20
    check (capacity_pcs between 5 and 50);

comment on column public.machines.capacity_kg  is 'Muatan maksimum dalam kiloan.';
comment on column public.machines.capacity_pcs is 'Muatan maksimum dalam satuan barang.';

-- ============================================================================
-- 2.2 Tabel permintaan_akun
-- ============================================================================
-- Menampung pendaftaran Admin dan permintaan lupa sandi, keduanya menunggu
-- persetujuan developer.

create table if not exists public.permintaan_akun (
  id                bigint generated by default as identity primary key,
  jenis             text not null check (jenis in ('Pendaftaran','Lupa Sandi')),
  username          text not null check (username = lower(username)
                     and username ~ '^[a-z0-9._-]{3,30}$'),
  full_name         text check (full_name is null
                     or length(btrim(full_name)) between 2 and 100),
  status            text not null default 'Menunggu'
                     check (status in ('Menunggu','Disetujui','Ditolak')),
  catatan           text check (catatan is null or length(catatan) <= 300),
  token_reset       text unique,
  token_hangus_pada timestamptz,
  token_terpakai    boolean not null default false,
  dibuat_pada       timestamptz not null default now(),
  diputuskan_pada   timestamptz,
  diputuskan_oleh   text
);

comment on table  public.permintaan_akun                 is 'Pendaftaran Admin dan permintaan lupa sandi yang menunggu persetujuan developer.';
comment on column public.permintaan_akun.token_reset     is 'Tautan pengaturan ulang sandi, sekali pakai.';
comment on column public.permintaan_akun.diputuskan_oleh is 'Siapa yang memutus. Diisi otomatis oleh fungsi putuskan_permintaan.';

-- Satu nama pengguna hanya boleh punya satu permintaan yang belum diputuskan.
-- Ini pengaman utama terhadap pengajuan ganda, ditegakkan di tingkat basis data.
create unique index if not exists permintaan_satu_menunggu
  on public.permintaan_akun (username)
  where status = 'Menunggu';

create index if not exists idx_permintaan_status
  on public.permintaan_akun (status, dibuat_pada desc);

create index if not exists idx_permintaan_token
  on public.permintaan_akun (token_reset)
  where token_reset is not null;

-- ============================================================================
-- 2.3 Keamanan baris permintaan_akun
-- ============================================================================
-- Gagal tertutup. Calon pengguna boleh mengajukan sendiri tetapi statusnya
-- dipaksa Menunggu. Tabel ini tidak boleh bisa dibaca publik karena berisi
-- daftar nama pengguna yang belum aktif.

alter table public.permintaan_akun enable row level security;

drop policy if exists permintaan_ajukan on public.permintaan_akun;
create policy permintaan_ajukan on public.permintaan_akun
  for insert to anon, authenticated
  with check (status = 'Menunggu');

drop policy if exists permintaan_baca on public.permintaan_akun;
create policy permintaan_baca on public.permintaan_akun
  for select to authenticated using (false);

-- ============================================================================
-- 2.4 Fungsi status_permintaan
-- ============================================================================
-- Pintu masuk berjalan sebagai tamu, sedangkan tabel ini sengaja tidak bisa
-- dibaca publik. Fungsi inilah jembatannya: menerima nama pengguna yang memang
-- sudah diketik pemakai, lalu hanya mengembalikan statusnya.
--
-- Tidak membocorkan apa pun tentang akun lain, karena yang bisa ditanya hanya
-- nama pengguna yang sudah diketahui penanyanya.

create or replace function public.status_permintaan(p_username text)
returns text            -- "Status|Jenis", atau null
language sql
security definer
set search_path = public, pg_temp
stable
as $$
  select status || '|' || jenis
    from public.permintaan_akun
   where username = lower(btrim(coalesce(p_username, '')))
   order by dibuat_pada desc
   limit 1
$$;

revoke execute on function public.status_permintaan(text) from public;
grant  execute on function public.status_permintaan(text) to anon, authenticated;

comment on function public.status_permintaan(text)
  is 'Status permintaan akun terakhir untuk sebuah nama pengguna.';

-- ============================================================================
-- 2.5 Fungsi pakai_token_reset
-- ============================================================================
-- Dipakai halaman /atur-sandi. Sekali jalan sudah mencakup semuanya: memeriksa
-- token masih sah, lalu menandainya terpakai supaya tidak bisa dipakai dua
-- kali. Mengembalikan id pengguna pemilik tautan, atau null bila tidak sah.

create or replace function public.pakai_token_reset(p_token text)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_id      bigint;
  v_user_id uuid;
begin
  select pa.id into v_id
    from public.permintaan_akun pa
   where pa.token_reset = coalesce(p_token, '')
     and pa.token_terpakai = false
     and pa.status = 'Disetujui'
     and pa.jenis = 'Lupa Sandi'
     and pa.token_hangus_pada > now()
   limit 1;

  if v_id is null then
    return null;
  end if;

  update public.permintaan_akun
     set token_terpakai = true
   where id = v_id;

  select pr.id into v_user_id
    from public.permintaan_akun pa
    join public.profiles pr on pr.username = pa.username
   where pa.id = v_id;

  return v_user_id;
end;
$$;

revoke execute on function public.pakai_token_reset(text) from anon, authenticated, public;

-- Pembacaan dan pemutusan dilakukan halaman developer yang berjalan dengan
-- SUPABASE_SERVICE_ROLE_KEY, sama seperti pola employee.controller.ts.

-- ============================================================================
-- 2.4 Fungsi putuskan_permintaan
-- ============================================================================
-- Sekalian menangani tiga hal: memutus permintaan, mengaktifkan akun bila
-- pendaftaran disetujui, dan menerbitkan tautan reset bila lupa sandi.

create or replace function public.putuskan_permintaan(
  p_id      bigint,
  p_setuju  boolean,
  p_catatan text default null
)
returns text          -- token reset, atau null
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_req   public.permintaan_akun;
  v_token text;
begin
  select * into v_req from public.permintaan_akun where id = p_id for update;
  if not found then
    raise exception 'Permintaan tidak ditemukan' using errcode = '22023';
  end if;

  if v_req.status <> 'Menunggu' then
    raise exception 'Permintaan sudah diputuskan' using errcode = '22023';
  end if;

  update public.permintaan_akun
     set status          = case when p_setuju then 'Disetujui' else 'Ditolak' end,
         catatan         = nullif(btrim(coalesce(p_catatan, '')), ''),
         diputuskan_pada = now(),
         diputuskan_oleh = 'developer'
   where id = p_id;

  if not p_setuju then
    -- Pendaftaran yang ditolak: akun tetap tidak aktif.
    return null;
  end if;

  if v_req.jenis = 'Pendaftaran' then
    update public.profiles
       set is_active = true
     where username = v_req.username;
    return null;
  end if;

  -- Lupa Sandi: terbitkan tautan sekali pakai, berlaku 30 menit.
  loop
    v_token := replace(gen_random_uuid()::text, '-', '')
             || replace(gen_random_uuid()::text, '-', '');
    exit when not exists (
      select 1 from public.permintaan_akun where token_reset = v_token
    );
  end loop;

  update public.permintaan_akun
     set token_reset       = v_token,
         token_hangus_pada = now() + interval '30 minutes',
         token_terpakai    = false
   where id = p_id;

  return v_token;
end;
$$;

revoke execute on function public.putuskan_permintaan(bigint,boolean,text)
  from anon, authenticated, public;

grant execute on function public.putuskan_permintaan(bigint,boolean,text)
  to service_role;

comment on function public.putuskan_permintaan(bigint,boolean,text)
  is 'Memutus permintaan akun. Dipanggil hanya dari halaman developer dengan service role key.';

commit;
